name: ${project.name}
version: ${plugin.version}
api-version: ${spigot.api.version}
description: ${project.description}

main: ${mainClass}

softdepend: [geSuitHomes, Multiverse-Core, My_Worlds, GriefPrevention, QuickShop, VanishNoPacket, Citizens, Votifier, Monolith, Minigames, MurderMystery, BuildBattle, VillageDefense, PrisonMines, ChatControlRed, RPlace, Konquest, Treasures]

loadbefore: [CommandHelper]

permissions:
  pandora.antibuild.bypass:
    default: op
  quickshop.allowinclaims:
    default: op
  trustedhomes.bypass:
    default: op
  pandora.command:
    default: op
  pandora.chatrepeat.bypass:
    default: op
  pandora.signlogger.listen:
    default: op
  pandora.signlogger.bypass:
    default: op
  pandora.tpclaim:
    default: op
  pandora.tpclaim.worlds:
    default: op
  pandora.claimslist:
    default: op
  pandora.claimselect:
    default: op
  pandora.flycancel.bypass:
    default: op
  vanish.silentjoin.global:
    default: false
    
  pandora.signs.color:
    default: false
  pandora.signs.format.bold:
    default: false
  pandora.signs.format.italic:
    default: false
  pandora.signs.format.strike:
    default: false
  pandora.signs.format.underline:
    default: false
  pandora.signs.format.magic:
    default: false
  pandora.signs.format.reset:
    default: false
  pandora.signs.format.*:
    default: false
    children:
      pandora.signs.format.bold: true
      pandora.signs.format.italic: true
      pandora.signs.format.strike: true
      pandora.signs.format.underline: true
      pandora.signs.format.magic: true
      pandora.signs.format.reset: true
  pandora.signs.format.normal:
    children:
      pandora.signs.format.bold: true
      pandora.signs.format.italic: true
      pandora.signs.format.strike: true
      pandora.signs.format.underline: true
      pandora.signs.format.reset: true
  pandora.signs.*:
    default: false
    children:
      pandora.signs.color: true
      pandora.signs.format.*: true
  pandora.itemdb:
    default: true
  pandora.item:
    default: op
  pandora.give:
    default: op
  pandora.giveall:
    default: op
  pandora.giveall.receive:
    description: Players with this permission can receive items from /giveall.
    default: true
  pandora.giveallworld:
    default: op
  pandora.spawner.change:
    default: op
  pandora.santahelper:
    default: op
  pandora.sparkler:
    default: op
  pandora.pvphandler.bypass:
    default: op
  pandora.pvphandler.ignore:
    default: op
  pandora.gpset:
    default: op
  pandora.movement.nohook:
    description: Players with this permission will not be able to be hooked with a fishing rod
    default: true
  pandora.movement.nopush:
    description: Players with this permission will not be able to be pushed by other players bumping them
    default: true
  pandora.movement.override.hook:
    description: Players with this permission will be able to hook players with a fishing rod regardless
    default: false
  pandora.booklogger.offline:
     description: Save book reports to file
     default: true
  pandora.booklogger.offline.report:
    description: This will allow offline reports to be loaded and reported in game.
    default: false
  pandora.slimechunk.show:
    description: Ability to detect slimechunks with /slimechunk
    default: false

commands:
  pandora:
    usage: /<command>
    permission: pandora.command
  tpclaim:
    usage: /<command> <player> [<index>|<world>|<world>:<index>]
    permission: pandora.tpclaim
  claimslist:
    usage: /<command> [<player> [<world>]]
    permission: pandora.claimslist
    aliases: [listclaims]
  claimselect:
    usage: /<command>
    permission: pandora.claimselect
  itemdb:
    usage: /<command> [<item> [<data>]]
    permission: pandora.itemdb
  item:
    usage: /<command> (<minecraftname> [<data> <amount> [<metadata>]]|<item|item:data> [<amount> [<metadata>]])
    permission: pandora.item
    aliases: [i]
  itemmeta:
    usage: /<command> [nbt]
    permission: pandora.itemmeta
  give:
    usage: /<command> <player> (<minecraftname> [<data> <amount> [<metadata>]]|<item|item:data> [<amount> [<metadata>]])
    permission: pandora.give
  giveall:
    usage: /<command> (<minecraftname> [<data> <amount> [<metadata>]]|<item|item:data> [<amount> [<metadata>]])
    permission: pandora.giveall
  giveallworld:
    usage: /<command> <world> (<minecraftname> [<data> <amount> [<metadata>]]|<item|item:data> [<amount> [<metadata>]])
    permission: pandora.giveallworld
  santahelper:
    usage: /<command> <world>
    permission: pandora.santahelper
  sparkler:
    usage: /<command> <ALL|player> [fire|smoke|colour]
    permission: pandora.sparkler
  gpset:
    usage: /<command> <name <name>|teleport>
    permission: pandora.gpset
  mgl:
    usage: /<command> <action>
    permission: pandora.minigamelocks.admin
  bookreport:
    usage: /<command> <player> <booknum>
    permission: pandora.booklogger.readbooks
  slimechunk:
    usage: /<command>
    permission: pandora.slimechunk.show
  mc:
    usage: /<command>
    permission: addstar.modchat
  hmc:
    usage: /<command>
    permission: addstar.headmodchat
  ac:
    usage: /<command>
    permission: addstar.adminchat
  broady:
    usage: /<command>
    permission: addstar.broady
  rawbcast:
    usage: /<command>
    permission: addstar.rawbcast
