name: Pandora
version: ${pom.version}

description: Bukkit plugin with many miscellaneous features specifically created for Addstar MC

main: au.com.addstar.pandora.MasterPlugin

softdepend: [Essentials, Multiverse-Core, GriefPrevention, QuickShop, VanishNoPacket, Citizens, Votifier]

loadbefore: [CommandHelper]

permissions:
  pandora.antibuild.bypass:
    default: op

  quickshop.allowinclaims:
    default: op
  trustedhomes.bypass:
    default: op
  pandora.command:
    default: op
  pandora.keyword-filter.listen:
    default: op
  pandora.chatrepeat.bypass:
    default: op
  pandora.signlogger.listen:
    default: op
  pandora.signlogger.bypass:
    default: op
  pandora.tpclaim:
    default: op
  pandora.flycancel.bypass:
    default: op
  vanish.silentjoin.global:
    default: false
    
  pandora.signs.color:
    default: false
  pandora.signs.format.bold:
    default: false
  pandora.signs.format.italic:
    default: false
  pandora.signs.format.strike:
    default: false
  pandora.signs.format.underline:
    default: false
  pandora.signs.format.magic:
    default: false
  pandora.signs.format.reset:
    default: false
  pandora.signs.format.*:
    default: false
    children:
      pandora.signs.format.bold: true
      pandora.signs.format.italic: true
      pandora.signs.format.strike: true
      pandora.signs.format.underline: true
      pandora.signs.format.magic: true
      pandora.signs.format.reset: true
  pandora.signs.format.normal:
    children:
      pandora.signs.format.bold: true
      pandora.signs.format.italic: true
      pandora.signs.format.strike: true
      pandora.signs.format.underline: true
      pandora.signs.format.reset: true
  pandora.signs.*:
    default: false
    children:
      pandora.signs.color: true
      pandora.signs.format.*: true
    
commands:
  pandora:
    usage: /<command>
    permission: pandora.command
  tpclaim:
    usage: /<command> <player> [<index>|<world>|<world>:<index>]
    permission: pandora.tpclaim
  ptimings:
    usage: /<command> <on|off>
    description: Turns timings on and off
    permission: bukkit.command.timings
  setblock:
    usage: /setblock <x> <y> <z> <tilename> [datavalue] [oldblockHandling] [dataTag]
    permission: minecraft.command.setblock