name: Pandora
version: ${pom.version}

description: Bukkit plugin with many miscellaneous features specifically created for Addstar MC

main: au.com.addstar.pandora.MasterPlugin

softdepend: [Essentials, Multiverse-Core, GriefPrevention, QuickShop, VanishNoPacket, Citizens]

permissions:
  quickshop.allowinclaims:
    default: op
  trustedhomes.bypass:
    default: op
  pandora.command:
    default: op
  pandora.keyword-filter.listen:
    default: op
    
commands:
  pandora:
    usage: /<command>
    permission: pandora.command
