name: Pandora
version: ${pom.version}

description: Bukkit plugin with many miscellaneous features specifically created for Addstar MC

main: au.com.addstar.pandora.MasterPlugin

softdepend: [Essentials, Multiverse-Core, GriefPrevention, QuickShop, VanishNoPacket, Citizens]

loadbefore: [CommandHelper]

permissions:
  quickshop.allowinclaims:
    default: op
  trustedhomes.bypass:
    default: op
  pandora.command:
    default: op
  pandora.keyword-filter.listen:
    default: op
  pandora.chatrepeat.bypass:
    default: op
  pandora.signlogger.listen:
    default: op
  pandora.signlogger.bypass:
    default: op
  pandora.tpclaim:
    default: op
  pandora.flycancel.bypass:
    default: op
  pandora.longcommands:
    default: op
    
commands:
  pandora:
    usage: /<command>
    permission: pandora.command
  tpclaim:
    usage: /<command> <player> [<index>|<world>|<world>:<index>]
    permission: pandora.tpclaim